# Generated by Django 5.1.3 on 2024-12-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_about_customuser_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('raiting', models.FloatField(default=0, max_length=1, verbose_name='Рейтинг')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'IT компании',
                'ordering': ['id'],
            },
        ),
    ]
