# Generated by Django 5.1.3 on 2024-12-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_membership_customuser_companies_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='cat',
        ),
        migrations.AddField(
            model_name='companies',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='companies', to='main.category', verbose_name='Категории'),
        ),
    ]
