# Generated by Django 5.1.3 on 2024-12-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_companies_cat_companies_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='main.companies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Представитель компании'),
        ),
    ]
