# Generated by Django 5.1.3 on 2024-12-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_review_options_remove_review_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.AddField(
            model_name='companies',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='companies',
            name='time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='review',
            name='finished_time',
            field=models.DateTimeField(blank=True, help_text='Укажите дату и время сдачи заказа', null=True, verbose_name='Время сдачи'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание заказа')),
                ('status', models.CharField(choices=[('pending', 'В ожидании ответа компании'), ('accepted', 'Принят компанией'), ('declined', 'Отклонен компанией'), ('completed_on_time', 'Выполнен в срок'), ('completed_late', 'Выполнен, но с нарушением сроков'), ('not_completed', 'Не выполнен'), ('rejected_by_client', 'Заказчик отказался принимать работу')], default='pending', max_length=50, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('delivery_time', models.DateTimeField(blank=True, help_text='Дата и время завершения заказа', null=True, verbose_name='Время сдачи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.companies', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Отзыв должен относиться к конкретному заказу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.order', verbose_name='Заказ'),
        ),
    ]
