# Generated by Django 5.1.3 on 2024-12-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_review_company_companies_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='finished_time',
        ),
        migrations.AlterField(
            model_name='companies',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.order', verbose_name='Заказ'),
        ),
    ]
