# Generated by Django 5.1.4 on 2024-12-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dead_line',
            field=models.DateTimeField(blank=True, help_text='время на выполнение', null=True, verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'В ожидании ответа компании'), ('accepted', 'Принят компанией'), ('declined', 'Отклонен компанией'), ('completed_at', 'Выполнен в срок:'), ('completed_late', 'Выполнен, но с нарушением сроков'), ('not_completed', 'Не выполнен'), ('rejected_by_client', 'Заказчик отказался принимать работу')], default='pending', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
