# Generated by Django 5.1.3 on 2024-12-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_dead_line_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Представитель компании'),
        ),
    ]
